# Generated by Django 3.0.7 on 2020-06-20 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=50)),
                ('des', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=20)),
                ('des', models.TextField()),
                ('audio', models.FileField(upload_to='audio/')),
                ('sub', models.CharField(choices=[('yearly', 'YEARLY'), ('monthly', 'MONTHLY')], default='MONTHLY', max_length=10)),
                ('date', models.DateField()),
                ('cg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoapi.Category')),
            ],
        ),
    ]
